language: python
python:
  - "2.7"

sudo: false

before_install:
  - wget -q http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ~/anaconda
  - export PATH=~/anaconda/bin:$PATH
  - conda update --yes --quiet conda

install:
  - conda create --yes -q -n pyenv python=$TRAVIS_PYTHON_VERSION pip numpy scipy cython
  - source activate pyenv
  - pip install pbr
  - pip install -r test-requirements.txt

script:
  - make travis

after_success: coveralls

#notifications:
  #email: silpa-discuss@nongnu.org
  #irc:
  #  channels:
  #  on_success: #silpa
  #  on_failure: #silpa
  #  use_notice: true
