language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

sudo: false

install:
  - pip install --user -r requirements.txt
  - pip install --user -r test-requirements.txt

script:
  - make travis

after_success: coveralls

notifications:
  email: silpa-discuss@nongnu.org
  irc:
    channels:
    on_success: #silpa
    on_failure: #silpa
    use_notice: true
